name: 🐛 Сообщение об ошибке
description: Сообщите об ошибке или проблеме
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Пожалуйста, заполните форму ниже.

  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Четкое и краткое описание проблемы
      placeholder: Опишите проблему...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Шаги для воспроизведения проблемы
      placeholder: |
        1. Перейти в '...'
        2. Нажать на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Четкое и краткое описание того, что вы ожидали увидеть
      placeholder: Опишите ожидаемое поведение...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
      description: Четкое и краткое описание того, что произошло на самом деле
      placeholder: Опишите фактическое поведение...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Скриншоты
      description: Если применимо, добавьте скриншоты, чтобы помочь объяснить вашу проблему
      placeholder: Перетащите скриншоты сюда или вставьте ссылки

  - type: dropdown
    id: environment
    attributes:
      label: Окружение
      description: В каком окружении возникла проблема?
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Версия
      description: Какая версия используется? (если применимо)
      placeholder: например, 1.0.0

  - type: textarea
    id: logs
    attributes:
      label: Логи/Ошибки
      description: Если есть логи или сообщения об ошибках, пожалуйста, вставьте их здесь
      placeholder: Вставьте логи или сообщения об ошибках...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Любая другая информация, которая может быть полезна
      placeholder: Дополнительная информация...

  - type: checkboxes
    id: terms
    attributes:
      label: Проверка
      description: Пожалуйста, подтвердите следующее
      options:
        - label: Я проверил, что эта проблема не была зарегистрирована ранее
          required: true
        - label: Я предоставил всю необходимую информацию для воспроизведения проблемы
          required: true
